name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -------------------------
  # API tests (only API csproj)
  # -------------------------
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore (API)
        run: dotnet restore ./tests/FeatureToggle.ApiTests/FeatureToggle.ApiTests.csproj

      - name: Test (API)
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        run: |
          dotnet test ./tests/FeatureToggle.ApiTests/FeatureToggle.ApiTests.csproj \
            --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=api-tests.trx"

      - name: Upload API artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: |
            tests/FeatureToggle.ApiTests/TestResults/**/*.trx
            tests/FeatureToggle.ApiTests/TestResults/**/coverage.cobertura.xml
          if-no-files-found: warn

  # ---------------------------------
  # Playwright UI smoke (C# / .NET 8)
  # ---------------------------------
  ui-smoke-csharp:
    name: UI smoke (Playwright .NET)
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore & Build UI tests
        run: |
          dotnet restore ./ui-tests-csharp/UiTests.csproj
          dotnet build   ./ui-tests-csharp/UiTests.csproj -c Release

      # Install Playwright browsers + Linux deps into the same output folder we will test from
      - name: Install Playwright browsers
        working-directory: ui-tests-csharp/bin/Release/net8.0
        run: pwsh ./ui-tests-csharp/bin/Release/net8.0/playwright.ps1 install --with-deps

      # Run under a virtual display on Linux (works whether your code is headless or headful)
      - name: Run UI smoke (C#) under Xvfb
        env:
          CI: true
          UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
          UI_USERNAME: ${{ secrets.UI_USERNAME }}
          UI_PASSWORD: ${{ secrets.UI_PASSWORD }}
        run: |
          xvfb-run -a dotnet test ./ui-tests-csharp/UiTests.csproj -c Release \
            --logger "trx;LogFileName=ui-csharp.trx"

      - name: Upload UI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-csharp-artifacts
          path: |
            ui-tests-csharp/TestResults/**/*.trx
            ui-tests-csharp/.auth/**
            ui-tests-csharp/**/playwright-report/**
            ui-tests-csharp/**/artifacts/**
            ui-tests-csharp/**/*.png
          if-no-files-found: warn

  # -------------
  # k6 smoke test
  # -------------
  k6-smoke:
    name: k6 smoke
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6@v1

      - name: Run k6
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        run: |
          mkdir -p k6-out
          k6 run k6/smoke.js --summary-export k6-out/summary.json

      - name: Upload k6 summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary
          path: k6-out/summary.json
          if-no-files-found: warn

  # ----------------
  # ZAP Baseline DAST
  # ----------------
  zap-baseline:
    name: ZAP Baseline (informational)
    runs-on: ubuntu-latest
    needs: [ui-smoke-csharp, k6-smoke]
    steps:
      - uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          target: ${{ secrets.UI_BASE_URL }}
          rules_file_name: .zap/rules.tsv
          artifact_name: zap-report
          cmd_options: >-
            -m 5
            -a
            -r zap-baseline.html
            -J zap-baseline.json

      # (Optional) also grab the files directly, in case you want them outside the Action’s own artifact
      - name: Upload ZAP artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-extra
          path: |
            zap-baseline.html
            zap-baseline.json
          if-no-files-found: warn
